Repository SNUH-BMI-LAB-Web-Project/snuh-bmilab-web-server, pull requests merged in 2025-06, with the labels that each got.

#9 refactor: 기존 코드 리팩터링 완료
  src/main/java/com/bmilab/backend/domain/leave/service/LeaveService.java
  src/main/java/com/bmilab/backend/domain/project/controller/ProjectController.java
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
  src/main/java/com/bmilab/backend/domain/project/service/RSSService.java
  src/main/java/com/bmilab/backend/domain/project/service/TimelineService.java
  src/main/java/com/bmilab/backend/domain/report/service/ReportService.java
  src/main/java/com/bmilab/backend/domain/user/controller/AdminUserController.java
  src/main/java/com/bmilab/backend/domain/user/dto/query/UserDetailQueryResult.java
  src/main/java/com/bmilab/backend/domain/user/repository/UserRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/user/service/UserService.java
Labels: ♻️ REFACTOR

#13 feat: 프로젝트 목록 조회에 PI 및 실무교수 키워드 필터 기능 추가
  src/main/java/com/bmilab/backend/domain/project/dto/condition/ProjectFilterCondition.java
  src/main/java/com/bmilab/backend/domain/project/repository/ProjectRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/user/repository/UserRepository.java
Labels: ✨ FEAT

#14 feat: 파일 저장 시 {UUID}_{파일이름}.{확장자} 형식 적용
  src/main/java/com/bmilab/backend/domain/file/controller/FileController.java
  src/main/java/com/bmilab/backend/domain/file/dto/request/UploadFileRequest.java
  src/main/java/com/bmilab/backend/domain/file/dto/response/FilePresignedUrlResponse.java
  src/main/java/com/bmilab/backend/domain/file/entity/FileInformation.java
  src/main/java/com/bmilab/backend/domain/file/service/FileService.java
Labels: ✨ FEAT

#20 refactor: 연구 분야를 Enum에서 테이블 객체로 변경
  src/main/java/com/bmilab/backend/domain/project/controller/ProjectApi.java
  src/main/java/com/bmilab/backend/domain/project/controller/ProjectController.java
  src/main/java/com/bmilab/backend/domain/project/dto/condition/ProjectFilterCondition.java
  src/main/java/com/bmilab/backend/domain/project/dto/query/GetAllProjectsQueryResult.java
  src/main/java/com/bmilab/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/com/bmilab/backend/domain/project/dto/response/ProjectDetail.java
  src/main/java/com/bmilab/backend/domain/project/dto/response/ProjectFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/project/entity/Project.java
  src/main/java/com/bmilab/backend/domain/project/enums/ProjectCategory.java
  src/main/java/com/bmilab/backend/domain/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/bmilab/backend/domain/project/repository/ProjectRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
  src/main/java/com/bmilab/backend/domain/projectcategory/controller/AdminProjectCategoryController.java
  src/main/java/com/bmilab/backend/domain/projectcategory/dto/request/ProjectCategoryRequest.java
  src/main/java/com/bmilab/backend/domain/projectcategory/dto/response/ProjectCategoryFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/projectcategory/dto/response/ProjectCategorySummary.java
  src/main/java/com/bmilab/backend/domain/projectcategory/entity/ProjectCategory.java
  src/main/java/com/bmilab/backend/domain/projectcategory/exception/ProjectCategoryErrorCode.java
  src/main/java/com/bmilab/backend/domain/projectcategory/repository/ProjectCategoryRepository.java
  src/main/java/com/bmilab/backend/domain/projectcategory/service/ProjectCategoryService.java
  src/main/java/com/bmilab/backend/domain/user/controller/AdminUserController.java
  src/main/java/com/bmilab/backend/domain/user/dto/query/UserInfoQueryResult.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/RegisterUserRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/UpdateUserRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/response/CurrentUserDetail.java
  src/main/java/com/bmilab/backend/domain/user/dto/response/UserDetail.java
  src/main/java/com/bmilab/backend/domain/user/dto/response/UserFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/user/entity/UserInfo.java
  src/main/java/com/bmilab/backend/domain/user/entity/UserProjectCategory.java
  src/main/java/com/bmilab/backend/domain/user/repository/UserProjectCategoryRepository.java
  src/main/java/com/bmilab/backend/domain/user/repository/UserRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/user/service/AuthService.java
  src/main/java/com/bmilab/backend/domain/user/service/UserService.java
Labels: ♻️ REFACTOR, ✨ FEAT

#22 refactor: 외부 교수를 DB 테이블로 관리하도록 수정
  src/main/java/com/bmilab/backend/domain/project/dto/ExternalProfessorSummary.java
  src/main/java/com/bmilab/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/com/bmilab/backend/domain/project/dto/response/ProjectDetail.java
  src/main/java/com/bmilab/backend/domain/project/dto/response/ProjectFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/project/entity/ExternalProfessor.java
  src/main/java/com/bmilab/backend/domain/project/entity/Project.java
  src/main/java/com/bmilab/backend/domain/project/event/ProjectUpdateEvent.java
  src/main/java/com/bmilab/backend/domain/project/event/listener/ProjectUpdateEventListener.java
  src/main/java/com/bmilab/backend/domain/project/repository/ExternalProfessorRepository.java
  src/main/java/com/bmilab/backend/domain/project/repository/ExternalProfessorRepositoryCustom.java
  src/main/java/com/bmilab/backend/domain/project/repository/ExternalProfessorRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
Labels: ♻️ REFACTOR
