Repository SNUH-BMI-LAB-Web-Project/snuh-bmilab-web-server, pull requests merged in 2025-08, with the labels that each got.

#77 feat: 외부 인사 전체 조회 시 이름 기준 오름차순 정렬 추가
  src/main/java/com/bmilab/backend/domain/project/repository/ExternalProfessorRepository.java
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
Labels: ✨ FEAT

#82 chore: 개발 서버 분기 처리 완료
  .github/workflows/ci-cd_dev.yml
  .github/workflows/ci-cd_prod.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🔧 CHORE

#78 feat: 게시판 고정글 개수 제한 및 비관적 락을 통한 동시성 처리
  src/main/java/com/bmilab/backend/domain/board/exception/BoardErrorCode.java
  src/main/java/com/bmilab/backend/domain/board/repository/BoardRepository.java
  src/main/java/com/bmilab/backend/domain/board/service/BoardService.java
  src/test/java/com/bmilab/backend/domain/board/service/BoardServiceTest.java
Labels: ✨ FEAT

#87 feat: 프로젝트 고정글 개수 제한 및 비관적 락을 통한 동시성 처리
  src/main/java/com/bmilab/backend/domain/project/exception/ProjectErrorCode.java
  src/main/java/com/bmilab/backend/domain/project/repository/ProjectRepository.java
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
  src/test/java/com/bmilab/backend/domain/project/service/ProjectServiceTest.java
Labels: ✨ FEAT

#88 feat: 업무보고 엑셀 다운로드/메일 전송 구현
  src/main/java/com/bmilab/backend/domain/report/controller/AdminReportApi.java
  src/main/java/com/bmilab/backend/domain/report/controller/AdminReportController.java
  src/main/java/com/bmilab/backend/domain/report/controller/ReportApi.java
  src/main/java/com/bmilab/backend/domain/report/controller/ReportController.java
  src/main/java/com/bmilab/backend/domain/report/repository/ReportRepository.java
  src/main/java/com/bmilab/backend/domain/report/repository/ReportRepositoryCustom.java
  src/main/java/com/bmilab/backend/domain/report/repository/ReportRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/report/service/ReportSchedulerService.java
  src/main/java/com/bmilab/backend/domain/report/service/ReportService.java
  src/main/java/com/bmilab/backend/domain/user/service/UserService.java
  src/main/java/com/bmilab/backend/global/email/EmailSender.java
  src/main/java/com/bmilab/backend/global/utils/ExcelGenerator.java
  src/main/java/com/bmilab/backend/global/utils/ExcelRow.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: ✨ FEAT

#89 feat: 파일 업로드 구조 리팩터링 및 게시판 이미지 처리 추가
  src/main/java/com/bmilab/backend/domain/board/dto/request/BoardRequest.java
  src/main/java/com/bmilab/backend/domain/board/service/BoardService.java
  src/main/java/com/bmilab/backend/domain/file/controller/FileApi.java
  src/main/java/com/bmilab/backend/domain/file/controller/FileController.java
  src/main/java/com/bmilab/backend/domain/file/dto/request/UploadFileRequest.java
  src/main/java/com/bmilab/backend/domain/file/enums/FileDomainType.java
  src/main/java/com/bmilab/backend/domain/file/repository/FileInformationRepository.java
  src/main/java/com/bmilab/backend/domain/file/service/FileSchedulerService.java
  src/main/java/com/bmilab/backend/domain/file/service/FileService.java
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
  src/main/java/com/bmilab/backend/domain/project/service/TimelineService.java
  src/main/java/com/bmilab/backend/domain/report/service/ReportService.java
  src/main/java/com/bmilab/backend/global/external/s3/S3Service.java
Labels: ♻️ REFACTOR, ✨ FEAT
