Repository SNUH-BMI-LAB-Web-Project/snuh-bmilab-web-server, pull requests merged in 2025-07, with the labels that each got.

#25 HOTFIX: 사용자 연구 분야 삭제 오류 수정
  src/main/java/com/bmilab/backend/domain/user/repository/UserProjectCategoryRepository.java
  src/main/java/com/bmilab/backend/domain/user/service/UserService.java
Labels: 🚑 HOTFIX

#30 refactor: 관리자 전용 일일 업무 보고 검색/필터 기능 분리 및 사용자 API 정리
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
  src/main/java/com/bmilab/backend/domain/report/controller/AdminReportApi.java
  src/main/java/com/bmilab/backend/domain/report/controller/AdminReportController.java
  src/main/java/com/bmilab/backend/domain/report/controller/ReportApi.java
  src/main/java/com/bmilab/backend/domain/report/controller/ReportController.java
  src/main/java/com/bmilab/backend/domain/report/repository/ReportRepositoryCustom.java
  src/main/java/com/bmilab/backend/domain/report/repository/ReportRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/report/service/ReportService.java
  src/main/java/com/bmilab/backend/domain/user/controller/AuthController.java
  src/main/java/com/bmilab/backend/domain/user/service/AuthService.java
Labels: ♻️ REFACTOR, ✨ FEAT

#32 docs: AdminProjectController용 Swagger 문서 인터페이스 생성
  src/main/java/com/bmilab/backend/domain/project/controller/AdminProjectApi.java
  src/main/java/com/bmilab/backend/domain/project/controller/AdminProjectController.java
Labels: 📝 DOCS

#35 feat: 연구 IRB, DRB 압축파일 다운로드 구현
  src/main/java/com/bmilab/backend/domain/file/service/FileService.java
  src/main/java/com/bmilab/backend/domain/project/controller/ProjectController.java
  src/main/java/com/bmilab/backend/domain/project/exception/ProjectErrorCode.java
  src/main/java/com/bmilab/backend/domain/project/repository/ProjectFileRepository.java
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
  src/main/java/com/bmilab/backend/global/external/s3/S3Service.java
Labels: ✨ FEAT

#37 HOTFIX: /user/search 기능 /user로 이동 및 기존 기능 복원
  src/main/java/com/bmilab/backend/domain/user/controller/UserApi.java
  src/main/java/com/bmilab/backend/domain/user/controller/UserController.java
  src/main/java/com/bmilab/backend/domain/user/dto/query/UserCondition.java
  src/main/java/com/bmilab/backend/domain/user/dto/query/UserSearchCondition.java
  src/main/java/com/bmilab/backend/domain/user/dto/response/SearchUserResponse.java
  src/main/java/com/bmilab/backend/domain/user/dto/response/UserFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/user/repository/UserRepository.java
  src/main/java/com/bmilab/backend/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/bmilab/backend/domain/user/repository/UserRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/user/service/UserService.java
Labels: 🚑 HOTFIX

#39 feat: DTO 유효성 검사(validation) 추가
  src/main/java/com/bmilab/backend/domain/file/controller/FileController.java
  src/main/java/com/bmilab/backend/domain/file/dto/request/UploadFileRequest.java
  src/main/java/com/bmilab/backend/domain/leave/controller/AdminLeaveController.java
  src/main/java/com/bmilab/backend/domain/leave/controller/LeaveController.java
  src/main/java/com/bmilab/backend/domain/leave/dto/request/ApplyLeaveRequest.java
  src/main/java/com/bmilab/backend/domain/leave/dto/request/RejectLeaveRequest.java
  src/main/java/com/bmilab/backend/domain/project/controller/AdminProjectController.java
  src/main/java/com/bmilab/backend/domain/project/controller/ProjectController.java
  src/main/java/com/bmilab/backend/domain/project/controller/TimelineController.java
  src/main/java/com/bmilab/backend/domain/project/dto/request/ExternalProfessorRequest.java
  src/main/java/com/bmilab/backend/domain/project/dto/request/ProjectCompleteRequest.java
  src/main/java/com/bmilab/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/com/bmilab/backend/domain/project/dto/request/TimelineRequest.java
  src/main/java/com/bmilab/backend/domain/projectcategory/controller/AdminProjectCategoryController.java
  src/main/java/com/bmilab/backend/domain/projectcategory/dto/request/ProjectCategoryRequest.java
  src/main/java/com/bmilab/backend/domain/report/controller/ReportController.java
  src/main/java/com/bmilab/backend/domain/report/dto/request/ReportRequest.java
  src/main/java/com/bmilab/backend/domain/user/controller/AdminUserController.java
  src/main/java/com/bmilab/backend/domain/user/controller/AuthController.java
  src/main/java/com/bmilab/backend/domain/user/controller/UserController.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/AdminUpdateUserRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/FindPasswordEmailRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/LoginRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/RegisterUserRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/UpdateUserPasswordRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/UpdateUserRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/UserAccountEmailRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/UserEducationRequest.java
  src/main/java/com/bmilab/backend/global/email/EmailSender.java
  src/main/java/com/bmilab/backend/global/validation/RegExp.java
Labels: ✨ FEAT

#43 feat: 사용자 소속 및 구분 관리 기능 추가 (주 소속, 서브 소속, 구분)
  src/main/java/com/bmilab/backend/domain/user/dto/request/AdminUpdateUserRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/RegisterUserRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/UpdateUserRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/UserAccountEmailRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/request/UserSubAffiliationRequest.java
  src/main/java/com/bmilab/backend/domain/user/dto/response/UserDetail.java
  src/main/java/com/bmilab/backend/domain/user/dto/response/UserFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/user/dto/response/UserSubAffiliationSummary.java
  src/main/java/com/bmilab/backend/domain/user/dto/response/UserSummary.java
  src/main/java/com/bmilab/backend/domain/user/entity/User.java
  src/main/java/com/bmilab/backend/domain/user/entity/UserSubAffiliation.java
  src/main/java/com/bmilab/backend/domain/user/enums/UserPosition.java
  src/main/java/com/bmilab/backend/domain/user/repository/UserRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/user/repository/UserSubAffiliationRepository.java
  src/main/java/com/bmilab/backend/domain/user/service/AuthService.java
  src/main/java/com/bmilab/backend/domain/user/service/UserService.java
Labels: ✨ FEAT

#46 feat: 토큰 만료기한 1시간으로 변경 및 토큰 검증 시 오류 응답 개선
  src/main/java/com/bmilab/backend/domain/user/service/AuthService.java
  src/main/java/com/bmilab/backend/global/exception/GlobalErrorCode.java
  src/main/java/com/bmilab/backend/global/jwt/TokenAuthenticationFilter.java
Labels: ✨ FEAT

#49 deploy: 개발 서버 CI/CD 구축
  .github/workflows/ci-cd_dev.yml
  .github/workflows/ci-cd_prod.yml
Labels: 🚀 DEPLOY

#56 feat: 게시판 및 카테고리 관리 기능 구현
  src/main/java/com/bmilab/backend/domain/board/controller/AdminBoardCategoryApi.java
  src/main/java/com/bmilab/backend/domain/board/controller/AdminBoardCategoryController.java
  src/main/java/com/bmilab/backend/domain/board/controller/BoardApi.java
  src/main/java/com/bmilab/backend/domain/board/controller/BoardCategoryApi.java
  src/main/java/com/bmilab/backend/domain/board/controller/BoardCategoryController.java
  src/main/java/com/bmilab/backend/domain/board/controller/BoardController.java
  src/main/java/com/bmilab/backend/domain/board/dto/query/GetAllBoardsQueryResult.java
  src/main/java/com/bmilab/backend/domain/board/dto/request/BoardCategoryReqeust.java
  src/main/java/com/bmilab/backend/domain/board/dto/request/BoardRequest.java
  src/main/java/com/bmilab/backend/domain/board/dto/response/BoardCategoryFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/board/dto/response/BoardCategorySummary.java
  src/main/java/com/bmilab/backend/domain/board/dto/response/BoardDetail.java
  src/main/java/com/bmilab/backend/domain/board/dto/response/BoardFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/board/entity/Board.java
  src/main/java/com/bmilab/backend/domain/board/entity/BoardCategory.java
  src/main/java/com/bmilab/backend/domain/board/exception/BoardErrorCode.java
  src/main/java/com/bmilab/backend/domain/board/repository/BoardCategoryRepository.java
  src/main/java/com/bmilab/backend/domain/board/repository/BoardRepository.java
  src/main/java/com/bmilab/backend/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/bmilab/backend/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/board/service/BoardCategoryService.java
  src/main/java/com/bmilab/backend/domain/board/service/BoardService.java
  src/main/java/com/bmilab/backend/domain/file/enums/FileDomainType.java
  src/main/java/com/bmilab/backend/domain/project/controller/ProjectController.java
  src/main/java/com/bmilab/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/com/bmilab/backend/domain/project/dto/response/ProjectFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/project/entity/Project.java
  src/main/java/com/bmilab/backend/domain/project/repository/ProjectRepository.java
  src/main/java/com/bmilab/backend/domain/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/bmilab/backend/domain/project/repository/ProjectRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
Labels: ✨ FEAT

#61 fix: 비밀번호 재발급 시 인증을 거치지 않도록 수정
  src/main/java/com/bmilab/backend/global/jwt/TokenAuthenticationFilter.java
Labels: 🚑 HOTFIX

#64 feat: 게시글 고정 기능 구현
  src/main/java/com/bmilab/backend/domain/board/controller/AdminBoardApi.java
  src/main/java/com/bmilab/backend/domain/board/controller/AdminBoardController.java
  src/main/java/com/bmilab/backend/domain/board/dto/request/BoardPinRequest.java
  src/main/java/com/bmilab/backend/domain/board/dto/response/BoardFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/board/entity/Board.java
  src/main/java/com/bmilab/backend/domain/board/exception/BoardErrorCode.java
  src/main/java/com/bmilab/backend/domain/board/repository/BoardRepository.java
  src/main/java/com/bmilab/backend/domain/board/service/BoardService.java
Labels: ✨ FEAT

#68 feat: 게시판 기능 개선 (고정글 정렬, 생성일시 추가, 카테고리 색상 필드)
  src/main/java/com/bmilab/backend/domain/board/dto/query/GetAllBoardsQueryResult.java
  src/main/java/com/bmilab/backend/domain/board/dto/request/BoardCategoryReqeust.java
  src/main/java/com/bmilab/backend/domain/board/dto/response/BoardDetail.java
  src/main/java/com/bmilab/backend/domain/board/dto/response/BoardFindAllResponse.java
  src/main/java/com/bmilab/backend/domain/board/entity/Board.java
  src/main/java/com/bmilab/backend/domain/board/entity/BoardCategory.java
  src/main/java/com/bmilab/backend/domain/board/repository/BoardRepository.java
  src/main/java/com/bmilab/backend/domain/board/repository/BoardRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/board/service/BoardCategoryService.java
  src/main/java/com/bmilab/backend/domain/board/service/BoardService.java
  src/main/java/com/bmilab/backend/global/validation/RegExp.java
Labels: ✨ FEAT

#71 feat: 연구 고정 기능 구현
  src/main/java/com/bmilab/backend/domain/board/controller/AdminBoardApi.java
  src/main/java/com/bmilab/backend/domain/board/controller/AdminBoardController.java
  src/main/java/com/bmilab/backend/domain/board/service/BoardService.java
  src/main/java/com/bmilab/backend/domain/project/controller/AdminProjectApi.java
  src/main/java/com/bmilab/backend/domain/project/controller/AdminProjectController.java
  src/main/java/com/bmilab/backend/domain/project/dto/request/ProjectPinRequest.java
  src/main/java/com/bmilab/backend/domain/project/entity/Project.java
  src/main/java/com/bmilab/backend/domain/project/exception/ProjectErrorCode.java
  src/main/java/com/bmilab/backend/domain/project/repository/ProjectRepositoryCustomImpl.java
  src/main/java/com/bmilab/backend/domain/project/service/ProjectService.java
Labels: ✨ FEAT
